[build]
  publish = "netlify/functions/server/public"
  functions = "netlify/functions"

[dev]
  command = "node netlify/functions/server/app.js"
  port = 3000
  publish = "netlify/functions/server/public"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  included_files = ["netlify/functions/server/**"] 