[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  included_files = ["!netlify/functions/server/node_modules/**"]
  [functions.server]
    node_bundler = "esbuild"
    included_files = ["views/**", "public/**", "models/**"] 