[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild" 